name: Bug Report
description: Signaler un bug ou un comportement inattendu
type: Bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Décrivez clairement le problème rencontré.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Étapes de reproduction
      description: Comment reproduire le bug ?
      placeholder: |
        1. Aller sur ...
        2. Cliquer sur ...
        3. Observer ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer ?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'écran
      description: Si applicable, ajoutez des captures d'écran.
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environnement
      description: "Navigateur, OS, résolution..."
      placeholder: "Chrome 120, macOS 15, 1920x1080"
    validations:
      required: false
